# Semverを超える範囲のアップデートがあれば通知する
name: Check incompatible updates

on:
  schedule:
    - cron: '0 0 * * *' # 毎日0時に実行
  workflow_dispatch:
  push:

jobs:
  check-incompatible-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - run: pnpm install

      # pnpmの既存仕様ではメジャーアップデートだけを抽出できないので苦肉の策。
      # Semver範囲内のアップデート対応は常に完了していることが前提。
      - name: Check updates
        run: |
          if $(pnpm outdated --compatible); then
            echo "no_compatible=yes" >> $GITHUB_ENV
          fi
          if ! $(pnpm outdated) ; then
          echo "incompatible=yes" >> $GITHUB_ENV
          fi

      - name: For debugging
        run: |
          echo no_compatible: ${{env.no_compatible}}
          echo incompatible: ${{env.incompatible}}

      # 設定時の作業ログ: https://yuuniworks.slack.com/archives/C01SHAR0VFA/p1722560200547789
      - name: Post to a Slack channel
        if: env.no_compatible == 'yes' && env.incompatible == 'yes'
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C07FK03HKG9'
          slack-message: 'durable-yearsにSemVer範囲外のがあります。'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
